export default {
    "ApplyNow": "Apply Now",
    "Landing": "We are a Coaching for Profits program that specializes in 6-max cash games. In our experience the CFP model is the best coaching model as the student’s and coaches goals are completely aligned. \n\n Our goal is to equip our students with the necessary skills required to move up to the highest stakes. To achieve this we teach a theoretically sound approach that uses efficient simplifications to achieve an implementable winning strategy.",
    "WhatWeOffer": "What We Offer",
    "TestimonialJakeMarples": "What separates Poker With Riske from the other coaching I've received before is that the program is incredibly organized and breaks complex ideas into well-structured, implementable heuristics. The community is very active and supportive, and through the program I've become more passionate about poker than I ever was before.",
    "TestimonialAdam": "I joined the CFP as a semi-recreational small winner at 50nl with a decent grasp of theory but not really able to apply it correctly. Poker With Riske completely transformed the way I think about poker and how to actually apply theory in all kinds of lineups. All the coaches are active players in todays games crushing 500nl+. The combination of knowledge the coaches are able to offer from theory/exploits to playing against recreational players is unbelievable. I'm now currently playing 200nl with 7-8bb/100 with an aim to crush even higher!",
    "TestimonialChrisD": "After a full year in the CFP, I can say without a doubt I wouldn’t be a fraction of the player I am today without Poker With Riske's help. I went from a small winner at 100NL, to beating 500NL. Something that felt completely out of reach a year ago.",
    "RyanRiskeSummary": "Ryan Riske graduated from the University of Western Ontario with a degree in Finance and Administration. He discovered online poker while getting his degree, and managed to turn a $50 deposit into over $40,000 while playing casually throughout college. After a few years in the 'real world' working as a consultant, Ryan decided that it wasn’t for him and left his job to play poker and stream on Twitch/YouTube. Ryan was crushing small stakes for several years while streaming on Twitch before his professional poker career took off. He met the rest of the PWR team while offering 1-on-1 poker coaching, and created this study group to level up faster. Within a year, Ryan moved up from 100z to 500NL + and has been beating those games ever since.",
    "AndrewIversSummary": "Andrew was formerly a pro gamer most notably competing for TSM and Renegades. He stumbled across poker while browsing Twitch and immediately fell in love with the game. After playing casually for 18 months, he decided to take a more serious approach to poker and hired Ryan as his coach. Working with Ryan gave him the skills and confidence to quit gaming and pursue poker full-time. Andrew's been crushing mid-high stakes since 2018 and attributes his success to working with Ryan, Gary and Connor over the last few years.",
    "ConnorArmstrongSummary": "Connor Armstrong studied Human Kinetics at the University of Guelph. Until recently, Connor competed as a professional ultimate frisbee player out of Toronto representing the Canadian national team in Poland, Australia and Germany. He discovered poker in 2015 during his freshman year of university, finding himself hooked after playing many strategy style games growing up. Connor played poker recreationally for close to a year before he decided to get serious and study with other players who were as interested as him. This led to meeting Ryan, Andrew and Gary. From there, the four of them quickly progressed through the stakes. These days, Connor's main games are 1knl - 5knl across various sites.",
    "OurCommunityText": "We have one simple motto - don't do it alone. While the Poker With Riske coaches found success as individuals, it was the daily collaboration and community that launched their professional careers in poker. Joining PWR means being a part of a community of people with the same goal of improving their game, day in, day out.Our Discord server is active around the clock. This is where students can share hand histories, discuss strategy and even hop on student-led study sessions. Our inclusive community is filled with hard working and driven individuals. Professional poker can be an isolated, lonesome grind, but with the PWR team, it doesn't have to be.",
    "SelectionProcessText": "Our application process is always open! If you are selected, we’ll contact you to schedule the first interview within 15 days. The phases of the selection process are as follows:",
    "Typeform": "https://pokerwithriske.typeform.com/to/fVw6HVJc",
};