export default {
    "ApplyNow": "Apply Now",
    "Landing": "We are a Coaching for Profits program that specializes in 6-max cash games. In our experience the CFP model is the best coaching model as the student’s and coaches goals are completely aligned. \n\n Our goal is to equip our students with the necessary skills required to move up to the highest stakes. To achieve this we teach a theoretically sound approach that uses efficient simplifications to achieve an implementable winning strategy.",
    "WhatWeOffer": "What We Offer",
    "TestimonialJakeMarples": "What separates Poker With Riske from the other coaching I've received before is that the program is incredibly organized and breaks complex ideas into well-structured, implementable heuristics. The community is very active and supportive, and through the program I've become more passionate about poker than I ever was before.",
    "TestimonialGrant": "My experience in the Poker with Riske CFP program has been everything that I hoped it would be. Prior to joining I was already a winning player but my time in the CFP has completely overhauled my game. The coaches do an excellent job of teaching as well as creating a friendly community that supports each other. I feel much more confident while at the tables in large part due to the consistent study schedule I developed during my year here. The program helped me progress from 200NL to consistently beating 500 and 1000NL.",
    "TestimonialMathias": "Before this CFP, I was a rake back pro—now I'm a poker player. My background involved millions of hands played in which my thought process were completely off, and I had overpaid great players to teach me, but they were not great coaches. At PWR, I found both and more, as they are all amazing people. With a well organized program, a super active dicord, and obviously a lot of work, I’ve been able to fix my game in all aspects I had major leaks in before, including my mindset. I went from playing 200nl as a rakeback pro, to playing the main event in Las Vegas—and now regularly play 500nl and 1K on .it sites (highest stakes available) with a 5.5 bb/100 results over 400k hands last year. The knowledge that these coaches gave to me is priceless, I'll be always thankful to this amazing school.",
    "RyanRiskeSummary": "Ryan Riske graduated from the University of Western Ontario with a degree in Finance and Administration. He discovered online poker while getting his degree, and managed to turn a $50 deposit into over $40,000 while playing casually throughout college. After a few years in the 'real world' working as a consultant, Ryan decided that it wasn’t for him and left his job to play poker and stream on Twitch/YouTube. Ryan was crushing small stakes for several years while streaming on Twitch before his professional poker career took off. He met the rest of the PWR team while offering 1-on-1 poker coaching, and created this study group to level up faster. Within a year, Ryan moved up from 100z to 500NL + and has been beating those games ever since.",
    "AndrewIversSummary": "Andrew was formerly a pro gamer most notably competing for TSM and Renegades. He stumbled across poker while browsing Twitch and immediately fell in love with the game. After playing casually for 18 months, he decided to take a more serious approach to poker and hired Ryan as his coach. Working with Ryan gave him the skills and confidence to quit gaming and pursue poker full-time. Andrew's been crushing mid-high stakes since 2018 and attributes his success to working with Ryan, Gary and Connor over the last few years.",
    "ConnorArmstrongSummary": "Connor Armstrong studied Human Kinetics at the University of Guelph. Until recently, Connor competed as a professional ultimate frisbee player out of Toronto representing the Canadian national team in Poland, Australia and Germany. He discovered poker in 2015 during his freshman year of university, finding himself hooked after playing many strategy style games growing up. Connor played poker recreationally for close to a year before he decided to get serious and study with other players who were as interested as him. This led to meeting Ryan, Andrew and Gary. From there, the four of them quickly progressed through the stakes. These days, Connor's main games are 1knl - 5knl across various sites.",
    "OurCommunityText": "We have one simple motto - don't do it alone. While the Poker With Riske coaches found success as individuals, it was the daily collaboration and community that launched their professional careers in poker. Joining PWR means being a part of a community of people with the same goal of improving their game, day in, day out.Our Discord server is active around the clock. This is where students can share hand histories, discuss strategy and even hop on student-led study sessions. Our inclusive community is filled with hard working and driven individuals. Professional poker can be an isolated, lonesome grind, but with the PWR team, it doesn't have to be.",
    "SelectionProcessText": "Our application process is always open! If you are selected, we’ll contact you to schedule the first interview within 15 days. The phases of the selection process are as follows:",
    "Typeform": "https://pokerwithriske.typeform.com/to/fVw6HVJc",
};